In [1]:
import pandas as pd

Pandas Functionlaties
1. Iterations
2. Sorting
3. Statistical Functions

4. Concat/Merge/Joining
5. Missing Data
6. Groupby aggregations
7. Date/Time
8. Data Visualization

In [2]:
df = pd.read_csv('food.csv')

In [3]:
df.head()

       title       cuisine      type  state famous location  taste  price
0       dosa  south indian   healthy  solid         chennai  spicy     60
1      maggi       chinese  fastfood  solid          hostel  spicy     30
2       susi      japanese   healthy  solid           tokyo  spicy    200
3   dal bati    rajasthani   healthy  mixed    chokhi dhani  spicy    150
4  pav bhaji  north indian  fastfood  mixed           delhi  spicy     60

### Iteration over DataFrames

In [4]:
for i in df:
    print(i)

title
cuisine
type
state
famous location
taste
price

In [5]:
for i in df:
    print(df[i])

0               dosa
1              maggi
2               susi
3           dal bati
4          pav bhaji
5              pizza
6             burger
7            noodles
8       litti chokha
9              curry
10           chapati
11             momos
12          sandwich
13             tacos
14          vada pav
15              maza
16          panipuri
17         coca cola
18              curd
19             lassi
20    chhole bhature
21               tea
22             pasta
23     chhole kulche
24      idli sambhar
25            coffee
26           lasgana
27            pastry
28             cakes
29          veg roll
30            kimchi
Name: title, dtype: object
0     south indian
1          chinese
2         japanese
3       rajasthani
4     north indian
5          italian
6          italian
7          chinese
8           bihari
9           indian
10          indian
11         chinese
12         italian
13         mexican
14          mumbai
15             USA
16    north indian
17             USA
18          indian
19         punjabi
20         punjabi
21          global
22         italian
23           delhi
24    south indian
25          global
26         italian
27          global
28          global
29         chinese
30          korean
Name: cuisine, dtype: object
0        healthy
1       fastfood
2        healthy
3        healthy
4       fastfood
5       fastfood
6       fastfood
7       fastfood
8        healthy
9        healthy
10       healthy
11      fastfood
12      fastfood
13      fastfood
14      fastfood
15    cold drink
16      fastfood
17    cold drink
18       healthy
19    cold drink
20      fastfood
21     hot drink
22      fastfood
23      fastfood
24       healthy
25         drink
26      fastfood
27        desert
28        desert
29      fastfood
30       healthy
Name: type, dtype: object
0      solid
1      solid
2      solid
3      mixed
4      mixed
5      solid
6      solid
7      solid
8      mixed
9     liquid
10     solid
11     solid
12     solid
13     solid
14     solid
15    liquid
16     mixed
17    liquid
18    liquid
19    liquid
20     mixed
21    liquid
22     solid
23     mixed
24     mixed
25    liquid
26     mixed
27     solid
28     solid
29     solid
30     solid
Name: state, dtype: object
0               chennai
1                hostel
2                 tokyo
3          chokhi dhani
4                 delhi
5                domino
6           burger king
7            china town
8                 patna
9              amritsar
10           sweet home
11       thapa ke momos
12                kanha
13                   GT
14       ghunghroo seth
15               bakery
16    golu ke gol gappe
17               bakery
18                dairy
19                dairy
20                delhi
21                gulab
22              cluster
23         amul parlour
24            dosa seth
25                  NBC
26      mamus in fusion
27               bakery
28               bakery
29         roll express
30                 seol
Name: famous location, dtype: object
0       spicy
1       spicy
2       spicy
3       spicy
4       spicy
5      cheesy
6       spicy
7       spicy
8       spicy
9       spicy
10    neutral
11      spicy
12      spicy
13      spicy
14      spicy
15      sweet
16      spicy
17      sweet
18      sweet
19      sweet
20      spicy
21      sweet
22      spicy
23      spicy
24      spicy
25      sweet
26    neutral
27      sweet
28      sweet
29      spicy
30      spicy
Name: taste, dtype: object
0      60
1      30
2     200
3     150
4      60
5     300
6      80
7      60
8     120
9     110
10     15
11     80
12     50
13    150
14     40
15     10
16     10
17     20
18     15
19     15
20     50
21      5
22    150
23     70
24     50
25     50
26    250
27     30
28    450
29     50
30    350
Name: price, dtype: int64

In [7]:
for i in df.values:
    print(i)
    break

['dosa' 'south indian' 'healthy' 'solid' 'chennai' 'spicy' 60]

* iteritems
* iterrows
* itertuples

In [9]:
for i in df.iteritems():
    print(i)
    break

('title', 0               dosa
1              maggi
2               susi
3           dal bati
4          pav bhaji
5              pizza
6             burger
7            noodles
8       litti chokha
9              curry
10           chapati
11             momos
12          sandwich
13             tacos
14          vada pav
15              maza
16          panipuri
17         coca cola
18              curd
19             lassi
20    chhole bhature
21               tea
22             pasta
23     chhole kulche
24      idli sambhar
25            coffee
26           lasgana
27            pastry
28             cakes
29          veg roll
30            kimchi
Name: title, dtype: object)

In [10]:
for ind, val in df.iteritems():
    print(ind)
    print(val)
    break

title
0               dosa
1              maggi
2               susi
3           dal bati
4          pav bhaji
5              pizza
6             burger
7            noodles
8       litti chokha
9              curry
10           chapati
11             momos
12          sandwich
13             tacos
14          vada pav
15              maza
16          panipuri
17         coca cola
18              curd
19             lassi
20    chhole bhature
21               tea
22             pasta
23     chhole kulche
24      idli sambhar
25            coffee
26           lasgana
27            pastry
28             cakes
29          veg roll
30            kimchi
Name: title, dtype: object

In [11]:
for i in df.iterrows():
    print(i)

(0, title                      dosa
cuisine            south indian
type                    healthy
state                     solid
famous location         chennai
taste                     spicy
price                        60
Name: 0, dtype: object)
(1, title                 maggi
cuisine             chinese
type               fastfood
state                 solid
famous location      hostel
taste                 spicy
price                    30
Name: 1, dtype: object)
(2, title                  susi
cuisine            japanese
type                healthy
state                 solid
famous location       tokyo
taste                 spicy
price                   200
Name: 2, dtype: object)
(3, title                  dal bati
cuisine              rajasthani
type                    healthy
state                     mixed
famous location    chokhi dhani
taste                     spicy
price                       150
Name: 3, dtype: object)
(4, title                 pav bhaji
cuisine            north indian
type                   fastfood
state                     mixed
famous location           delhi
taste                     spicy
price                        60
Name: 4, dtype: object)
(5, title                 pizza
cuisine             italian
type               fastfood
state                 solid
famous location      domino
taste                cheesy
price                   300
Name: 5, dtype: object)
(6, title                   burger
cuisine                italian
type                  fastfood
state                    solid
famous location    burger king
taste                    spicy
price                       80
Name: 6, dtype: object)
(7, title                 noodles
cuisine               chinese
type                 fastfood
state                   solid
famous location    china town
taste                   spicy
price                      60
Name: 7, dtype: object)
(8, title              litti chokha
cuisine                  bihari
type                    healthy
state                     mixed
famous location           patna
taste                     spicy
price                       120
Name: 8, dtype: object)
(9, title                 curry
cuisine              indian
type                healthy
state                liquid
famous location    amritsar
taste                 spicy
price                   110
Name: 9, dtype: object)
(10, title                 chapati
cuisine                indian
type                  healthy
state                   solid
famous location    sweet home
taste                 neutral
price                      15
Name: 10, dtype: object)
(11, title                       momos
cuisine                   chinese
type                     fastfood
state                       solid
famous location    thapa ke momos
taste                       spicy
price                          80
Name: 11, dtype: object)
(12, title              sandwich
cuisine             italian
type               fastfood
state                 solid
famous location       kanha
taste                 spicy
price                    50
Name: 12, dtype: object)
(13, title                 tacos
cuisine             mexican
type               fastfood
state                 solid
famous location          GT
taste                 spicy
price                   150
Name: 13, dtype: object)
(14, title                    vada pav
cuisine                    mumbai
type                     fastfood
state                       solid
famous location    ghunghroo seth
taste                       spicy
price                          40
Name: 14, dtype: object)
(15, title                    maza
cuisine                   USA
type               cold drink
state                  liquid
famous location        bakery
taste                   sweet
price                      10
Name: 15, dtype: object)
(16, title                       panipuri
cuisine                 north indian
type                        fastfood
state                          mixed
famous location    golu ke gol gappe
taste                          spicy
price                             10
Name: 16, dtype: object)
(17, title               coca cola
cuisine                   USA
type               cold drink
state                  liquid
famous location        bakery
taste                   sweet
price                      20
Name: 17, dtype: object)
(18, title                 curd
cuisine             indian
type               healthy
state               liquid
famous location      dairy
taste                sweet
price                   15
Name: 18, dtype: object)
(19, title                   lassi
cuisine               punjabi
type               cold drink
state                  liquid
famous location         dairy
taste                   sweet
price                      15
Name: 19, dtype: object)
(20, title              chhole bhature
cuisine                   punjabi
type                     fastfood
state                       mixed
famous location             delhi
taste                       spicy
price                          50
Name: 20, dtype: object)
(21, title                    tea
cuisine               global
type               hot drink
state                 liquid
famous location        gulab
taste                  sweet
price                      5
Name: 21, dtype: object)
(22, title                 pasta
cuisine             italian
type               fastfood
state                 solid
famous location     cluster
taste                 spicy
price                   150
Name: 22, dtype: object)
(23, title              chhole kulche
cuisine                    delhi
type                    fastfood
state                      mixed
famous location     amul parlour
taste                      spicy
price                         70
Name: 23, dtype: object)
(24, title              idli sambhar
cuisine            south indian
type                    healthy
state                     mixed
famous location       dosa seth
taste                     spicy
price                        50
Name: 24, dtype: object)
(25, title              coffee
cuisine            global
type                drink
state              liquid
famous location       NBC
taste               sweet
price                  50
Name: 25, dtype: object)
(26, title                      lasgana
cuisine                    italian
type                      fastfood
state                        mixed
famous location    mamus in fusion
taste                      neutral
price                          250
Name: 26, dtype: object)
(27, title              pastry
cuisine            global
type               desert
state               solid
famous location    bakery
taste               sweet
price                  30
Name: 27, dtype: object)
(28, title               cakes
cuisine            global
type               desert
state               solid
famous location    bakery
taste               sweet
price                 450
Name: 28, dtype: object)
(29, title                  veg roll
cuisine                 chinese
type                   fastfood
state                     solid
famous location    roll express
taste                     spicy
price                        50
Name: 29, dtype: object)
(30, title               kimchi
cuisine             korean
type               healthy
state                solid
famous location       seol
taste                spicy
price                  350
Name: 30, dtype: object)

In [14]:
for ind,row in df.iterrows():
    print(ind)
    print(row)
    print(row['type'])
    break

0
title                      dosa
cuisine            south indian
type                    healthy
state                     solid
famous location         chennai
taste                     spicy
price                        60
Name: 0, dtype: object
healthy

In [15]:
for i in df.itertuples():
    print(i)

Pandas(Index=0, title='dosa', cuisine='south indian', type='healthy', state='solid', _5='chennai', taste='spicy', price=60)
Pandas(Index=1, title='maggi', cuisine='chinese', type='fastfood', state='solid', _5='hostel', taste='spicy', price=30)
Pandas(Index=2, title='susi', cuisine='japanese', type='healthy', state='solid', _5='tokyo', taste='spicy', price=200)
Pandas(Index=3, title='dal bati', cuisine='rajasthani', type='healthy', state='mixed', _5='chokhi dhani', taste='spicy', price=150)
Pandas(Index=4, title='pav bhaji', cuisine='north indian', type='fastfood', state='mixed', _5='delhi', taste='spicy', price=60)
Pandas(Index=5, title='pizza', cuisine='italian', type='fastfood', state='solid', _5='domino', taste='cheesy', price=300)
Pandas(Index=6, title='burger', cuisine='italian', type='fastfood', state='solid', _5='burger king', taste='spicy', price=80)
Pandas(Index=7, title='noodles', cuisine='chinese', type='fastfood', state='solid', _5='china town', taste='spicy', price=60)
Pandas(Index=8, title='litti chokha', cuisine='bihari', type='healthy', state='mixed', _5='patna', taste='spicy', price=120)
Pandas(Index=9, title='curry', cuisine='indian', type='healthy', state='liquid', _5='amritsar', taste='spicy', price=110)
Pandas(Index=10, title='chapati', cuisine='indian', type='healthy', state='solid', _5='sweet home', taste='neutral', price=15)
Pandas(Index=11, title='momos', cuisine='chinese', type='fastfood', state='solid', _5='thapa ke momos', taste='spicy', price=80)
Pandas(Index=12, title='sandwich', cuisine='italian', type='fastfood', state='solid', _5='kanha', taste='spicy', price=50)
Pandas(Index=13, title='tacos', cuisine='mexican', type='fastfood', state='solid', _5='GT', taste='spicy', price=150)
Pandas(Index=14, title='vada pav', cuisine='mumbai', type='fastfood', state='solid', _5='ghunghroo seth', taste='spicy', price=40)
Pandas(Index=15, title='maza', cuisine='USA', type='cold drink', state='liquid', _5='bakery', taste='sweet', price=10)
Pandas(Index=16, title='panipuri', cuisine='north indian', type='fastfood', state='mixed', _5='golu ke gol gappe', taste='spicy', price=10)
Pandas(Index=17, title='coca cola', cuisine='USA', type='cold drink', state='liquid', _5='bakery', taste='sweet', price=20)
Pandas(Index=18, title='curd', cuisine='indian', type='healthy', state='liquid', _5='dairy', taste='sweet', price=15)
Pandas(Index=19, title='lassi', cuisine='punjabi', type='cold drink', state='liquid', _5='dairy', taste='sweet', price=15)
Pandas(Index=20, title='chhole bhature', cuisine='punjabi', type='fastfood', state='mixed', _5='delhi', taste='spicy', price=50)
Pandas(Index=21, title='tea', cuisine='global', type='hot drink', state='liquid', _5='gulab', taste='sweet', price=5)
Pandas(Index=22, title='pasta', cuisine='italian', type='fastfood', state='solid', _5='cluster', taste='spicy', price=150)
Pandas(Index=23, title='chhole kulche', cuisine='delhi', type='fastfood', state='mixed', _5='amul parlour', taste='spicy', price=70)
Pandas(Index=24, title='idli sambhar', cuisine='south indian', type='healthy', state='mixed', _5='dosa seth', taste='spicy', price=50)
Pandas(Index=25, title='coffee', cuisine='global', type='drink', state='liquid', _5='NBC', taste='sweet', price=50)
Pandas(Index=26, title='lasgana', cuisine='italian', type='fastfood', state='mixed', _5='mamus in fusion', taste='neutral', price=250)
Pandas(Index=27, title='pastry', cuisine='global', type='desert', state='solid', _5='bakery', taste='sweet', price=30)
Pandas(Index=28, title='cakes', cuisine='global', type='desert', state='solid', _5='bakery', taste='sweet', price=450)
Pandas(Index=29, title='veg roll', cuisine='chinese', type='fastfood', state='solid', _5='roll express', taste='spicy', price=50)
Pandas(Index=30, title='kimchi', cuisine='korean', type='healthy', state='solid', _5='seol', taste='spicy', price=350)

In [16]:
for i in df.itertuples():
    print(i)
    break

Pandas(Index=0, title='dosa', cuisine='south indian', type='healthy', state='solid', _5='chennai', taste='spicy', price=60)

In [17]:
i

Pandas(Index=0, title='dosa', cuisine='south indian', type='healthy', state='solid', _5='chennai', taste='spicy', price=60)

In [18]:
i[0]

0

In [19]:
i[1]

'dosa'

In [20]:
i[2]

'south indian'

In [21]:
i['title']

TypeError: tuple indices must be integers or slices, not str

In [22]:
i.title

'dosa'

### Sorting

In [23]:
df.head()

       title       cuisine      type  state famous location  taste  price
0       dosa  south indian   healthy  solid         chennai  spicy     60
1      maggi       chinese  fastfood  solid          hostel  spicy     30
2       susi      japanese   healthy  solid           tokyo  spicy    200
3   dal bati    rajasthani   healthy  mixed    chokhi dhani  spicy    150
4  pav bhaji  north indian  fastfood  mixed           delhi  spicy     60

In [24]:
df.sort_values('title')

,title,cuisine,type,state,famous location,taste,price
6,burger,italian,fastfood,solid,burger king,spicy,80
28,cakes,global,desert,solid,bakery,sweet,450
10,chapati,indian,healthy,solid,sweet home,neutral,15
20,chhole bhature,punjabi,fastfood,mixed,delhi,spicy,50
23,chhole kulche,delhi,fastfood,mixed,amul parlour,spicy,70
17,coca cola,USA,cold drink,liquid,bakery,sweet,20
25,coffee,global,drink,liquid,NBC,sweet,50
18,curd,indian,healthy,liquid,dairy,sweet,15
9,curry,indian,healthy,liquid,amritsar,spicy,110
3,dal bati,rajasthani,healthy,mixed,chokhi dhani,spicy,150
0,dosa,south indian,healthy,solid,chennai,spicy,60
24,idli sambhar,south indian,healthy,mixed,dosa seth,spicy,50
30,kimchi,korean,healthy,solid,seol,spicy,350
26,lasgana,italian,fastfood,mixed,mamus in fusion,neutral,250
19,lassi,punjabi,cold drink,liquid,dairy,sweet,15
8,litti chokha,bihari,healthy,mixed,patna,spicy,120
1,maggi,chinese,fastfood,solid,hostel,spicy,30
15,maza,USA,cold drink,liquid,bakery,sweet,10
11,momos,chinese,fastfood,solid,thapa ke momos,spicy,80
7,noodles,chinese,fastfood,solid,china town,spicy,60
16,panipuri,north indian,fastfood,mixed,golu ke gol gappe,spicy,10
22,pasta,italian,fastfood,solid,cluster,spicy,150
27,pastry,global,desert,solid,bakery,sweet,30
4,pav bhaji,north indian,fastfood,mixed,delhi,spicy,60
5,pizza,italian,fastfood,solid,domino,cheesy,300
12,sandwich,italian,fastfood,solid,kanha,spicy,50
2,susi,japanese,healthy,solid,tokyo,spicy,200
13,tacos,mexican,fastfood,solid,GT,spicy,150
21,tea,global,hot drink,liquid,gulab,sweet,5
14,vada pav,mumbai,fastfood,solid,ghunghroo seth,spicy,40
29,veg roll,chinese,fastfood,solid,roll express,spicy,50

In [25]:
df.sort_values('title',ascending=False)

,title,cuisine,type,state,famous location,taste,price
29,veg roll,chinese,fastfood,solid,roll express,spicy,50
14,vada pav,mumbai,fastfood,solid,ghunghroo seth,spicy,40
21,tea,global,hot drink,liquid,gulab,sweet,5
13,tacos,mexican,fastfood,solid,GT,spicy,150
2,susi,japanese,healthy,solid,tokyo,spicy,200
12,sandwich,italian,fastfood,solid,kanha,spicy,50
5,pizza,italian,fastfood,solid,domino,cheesy,300
4,pav bhaji,north indian,fastfood,mixed,delhi,spicy,60
27,pastry,global,desert,solid,bakery,sweet,30
22,pasta,italian,fastfood,solid,cluster,spicy,150
16,panipuri,north indian,fastfood,mixed,golu ke gol gappe,spicy,10
7,noodles,chinese,fastfood,solid,china town,spicy,60
11,momos,chinese,fastfood,solid,thapa ke momos,spicy,80
15,maza,USA,cold drink,liquid,bakery,sweet,10
1,maggi,chinese,fastfood,solid,hostel,spicy,30
8,litti chokha,bihari,healthy,mixed,patna,spicy,120
19,lassi,punjabi,cold drink,liquid,dairy,sweet,15
26,lasgana,italian,fastfood,mixed,mamus in fusion,neutral,250
30,kimchi,korean,healthy,solid,seol,spicy,350
24,idli sambhar,south indian,healthy,mixed,dosa seth,spicy,50
0,dosa,south indian,healthy,solid,chennai,spicy,60
3,dal bati,rajasthani,healthy,mixed,chokhi dhani,spicy,150
9,curry,indian,healthy,liquid,amritsar,spicy,110
18,curd,indian,healthy,liquid,dairy,sweet,15
25,coffee,global,drink,liquid,NBC,sweet,50
17,coca cola,USA,cold drink,liquid,bakery,sweet,20
23,chhole kulche,delhi,fastfood,mixed,amul parlour,spicy,70
20,chhole bhature,punjabi,fastfood,mixed,delhi,spicy,50
10,chapati,indian,healthy,solid,sweet home,neutral,15
28,cakes,global,desert,solid,bakery,sweet,450
6,burger,italian,fastfood,solid,burger king,spicy,80

In [26]:
df.sort_values('title',ascending=False,ignore_index=True)

,title,cuisine,type,state,famous location,taste,price
0,veg roll,chinese,fastfood,solid,roll express,spicy,50
1,vada pav,mumbai,fastfood,solid,ghunghroo seth,spicy,40
2,tea,global,hot drink,liquid,gulab,sweet,5
3,tacos,mexican,fastfood,solid,GT,spicy,150
4,susi,japanese,healthy,solid,tokyo,spicy,200
5,sandwich,italian,fastfood,solid,kanha,spicy,50
6,pizza,italian,fastfood,solid,domino,cheesy,300
7,pav bhaji,north indian,fastfood,mixed,delhi,spicy,60
8,pastry,global,desert,solid,bakery,sweet,30
9,pasta,italian,fastfood,solid,cluster,spicy,150
10,panipuri,north indian,fastfood,mixed,golu ke gol gappe,spicy,10
11,noodles,chinese,fastfood,solid,china town,spicy,60
12,momos,chinese,fastfood,solid,thapa ke momos,spicy,80
13,maza,USA,cold drink,liquid,bakery,sweet,10
14,maggi,chinese,fastfood,solid,hostel,spicy,30
15,litti chokha,bihari,healthy,mixed,patna,spicy,120
16,lassi,punjabi,cold drink,liquid,dairy,sweet,15
17,lasgana,italian,fastfood,mixed,mamus in fusion,neutral,250
18,kimchi,korean,healthy,solid,seol,spicy,350
19,idli sambhar,south indian,healthy,mixed,dosa seth,spicy,50
20,dosa,south indian,healthy,solid,chennai,spicy,60
21,dal bati,rajasthani,healthy,mixed,chokhi dhani,spicy,150
22,curry,indian,healthy,liquid,amritsar,spicy,110
23,curd,indian,healthy,liquid,dairy,sweet,15
24,coffee,global,drink,liquid,NBC,sweet,50
25,coca cola,USA,cold drink,liquid,bakery,sweet,20
26,chhole kulche,delhi,fastfood,mixed,amul parlour,spicy,70
27,chhole bhature,punjabi,fastfood,mixed,delhi,spicy,50
28,chapati,indian,healthy,solid,sweet home,neutral,15
29,cakes,global,desert,solid,bakery,sweet,450
30,burger,italian,fastfood,solid,burger king,spicy,80

In [27]:
df.sort_values('type',ascending=False)

,title,cuisine,type,state,famous location,taste,price
21,tea,global,hot drink,liquid,gulab,sweet,5
0,dosa,south indian,healthy,solid,chennai,spicy,60
8,litti chokha,bihari,healthy,mixed,patna,spicy,120
24,idli sambhar,south indian,healthy,mixed,dosa seth,spicy,50
18,curd,indian,healthy,liquid,dairy,sweet,15
10,chapati,indian,healthy,solid,sweet home,neutral,15
9,curry,indian,healthy,liquid,amritsar,spicy,110
30,kimchi,korean,healthy,solid,seol,spicy,350
2,susi,japanese,healthy,solid,tokyo,spicy,200
3,dal bati,rajasthani,healthy,mixed,chokhi dhani,spicy,150
7,noodles,chinese,fastfood,solid,china town,spicy,60
29,veg roll,chinese,fastfood,solid,roll express,spicy,50
26,lasgana,italian,fastfood,mixed,mamus in fusion,neutral,250
23,chhole kulche,delhi,fastfood,mixed,amul parlour,spicy,70
22,pasta,italian,fastfood,solid,cluster,spicy,150
20,chhole bhature,punjabi,fastfood,mixed,delhi,spicy,50
6,burger,italian,fastfood,solid,burger king,spicy,80
4,pav bhaji,north indian,fastfood,mixed,delhi,spicy,60
16,panipuri,north indian,fastfood,mixed,golu ke gol gappe,spicy,10
1,maggi,chinese,fastfood,solid,hostel,spicy,30
14,vada pav,mumbai,fastfood,solid,ghunghroo seth,spicy,40
13,tacos,mexican,fastfood,solid,GT,spicy,150
12,sandwich,italian,fastfood,solid,kanha,spicy,50
11,momos,chinese,fastfood,solid,thapa ke momos,spicy,80
5,pizza,italian,fastfood,solid,domino,cheesy,300
25,coffee,global,drink,liquid,NBC,sweet,50
28,cakes,global,desert,solid,bakery,sweet,450
27,pastry,global,desert,solid,bakery,sweet,30
19,lassi,punjabi,cold drink,liquid,dairy,sweet,15
17,coca cola,USA,cold drink,liquid,bakery,sweet,20
15,maza,USA,cold drink,liquid,bakery,sweet,10

In [28]:
df.sort_values('type',ascending=False, key= lambda x:x.str.len())

,title,cuisine,type,state,famous location,taste,price
15,maza,USA,cold drink,liquid,bakery,sweet,10
17,coca cola,USA,cold drink,liquid,bakery,sweet,20
19,lassi,punjabi,cold drink,liquid,dairy,sweet,15
21,tea,global,hot drink,liquid,gulab,sweet,5
26,lasgana,italian,fastfood,mixed,mamus in fusion,neutral,250
12,sandwich,italian,fastfood,solid,kanha,spicy,50
29,veg roll,chinese,fastfood,solid,roll express,spicy,50
16,panipuri,north indian,fastfood,mixed,golu ke gol gappe,spicy,10
1,maggi,chinese,fastfood,solid,hostel,spicy,30
14,vada pav,mumbai,fastfood,solid,ghunghroo seth,spicy,40
13,tacos,mexican,fastfood,solid,GT,spicy,150
11,momos,chinese,fastfood,solid,thapa ke momos,spicy,80
4,pav bhaji,north indian,fastfood,mixed,delhi,spicy,60
20,chhole bhature,punjabi,fastfood,mixed,delhi,spicy,50
23,chhole kulche,delhi,fastfood,mixed,amul parlour,spicy,70
7,noodles,chinese,fastfood,solid,china town,spicy,60
6,burger,italian,fastfood,solid,burger king,spicy,80
5,pizza,italian,fastfood,solid,domino,cheesy,300
22,pasta,italian,fastfood,solid,cluster,spicy,150
24,idli sambhar,south indian,healthy,mixed,dosa seth,spicy,50
0,dosa,south indian,healthy,solid,chennai,spicy,60
18,curd,indian,healthy,liquid,dairy,sweet,15
10,chapati,indian,healthy,solid,sweet home,neutral,15
9,curry,indian,healthy,liquid,amritsar,spicy,110
8,litti chokha,bihari,healthy,mixed,patna,spicy,120
3,dal bati,rajasthani,healthy,mixed,chokhi dhani,spicy,150
2,susi,japanese,healthy,solid,tokyo,spicy,200
30,kimchi,korean,healthy,solid,seol,spicy,350
27,pastry,global,desert,solid,bakery,sweet,30
28,cakes,global,desert,solid,bakery,sweet,450
25,coffee,global,drink,liquid,NBC,sweet,50

In [29]:
d = pd.DataFrame({'name':['Aakash Mall','Aditya Kumar','Aditya Raj','Daksh Yogi','Gargi Rewar','Jayesh Gupta']})
d

           name
0   Aakash Mall
1  Aditya Kumar
2    Aditya Raj
3    Daksh Yogi
4   Gargi Rewar
5  Jayesh Gupta

In [41]:
d['name'].str.split().str.get(-1).sort_values()

5    Gupta
1    Kumar
0     Mall
2      Raj
4    Rewar
3     Yogi
Name: name, dtype: object

In [39]:
d.sort_values(by='name',ascending=False, key=lambda x:x.str.split().str.get(-1))

           name
3    Daksh Yogi
4   Gargi Rewar
2    Aditya Raj
0   Aakash Mall
1  Aditya Kumar
5  Jayesh Gupta

In [45]:
df['type'].value_counts()

fastfood      15
healthy        9
cold drink     3
desert         2
hot drink      1
drink          1
Name: type, dtype: int64

In [43]:
df['type'].value_counts().sort_index()

cold drink     3
desert         2
drink          1
fastfood      15
healthy        9
hot drink      1
Name: type, dtype: int64

In [44]:
df['type'].value_counts().sort_values()

hot drink      1
drink          1
desert         2
cold drink     3
healthy        9
fastfood      15
Name: type, dtype: int64

In [46]:
df.sort_index(axis=1)

,cuisine,famous location,price,state,taste,title,type
0,south indian,chennai,60,solid,spicy,dosa,healthy
1,chinese,hostel,30,solid,spicy,maggi,fastfood
2,japanese,tokyo,200,solid,spicy,susi,healthy
3,rajasthani,chokhi dhani,150,mixed,spicy,dal bati,healthy
4,north indian,delhi,60,mixed,spicy,pav bhaji,fastfood
5,italian,domino,300,solid,cheesy,pizza,fastfood
6,italian,burger king,80,solid,spicy,burger,fastfood
7,chinese,china town,60,solid,spicy,noodles,fastfood
8,bihari,patna,120,mixed,spicy,litti chokha,healthy
9,indian,amritsar,110,liquid,spicy,curry,healthy
10,indian,sweet home,15,solid,neutral,chapati,healthy
11,chinese,thapa ke momos,80,solid,spicy,momos,fastfood
12,italian,kanha,50,solid,spicy,sandwich,fastfood
13,mexican,GT,150,solid,spicy,tacos,fastfood
14,mumbai,ghunghroo seth,40,solid,spicy,vada pav,fastfood
15,USA,bakery,10,liquid,sweet,maza,cold drink
16,north indian,golu ke gol gappe,10,mixed,spicy,panipuri,fastfood
17,USA,bakery,20,liquid,sweet,coca cola,cold drink
18,indian,dairy,15,liquid,sweet,curd,healthy
19,punjabi,dairy,15,liquid,sweet,lassi,cold drink
20,punjabi,delhi,50,mixed,spicy,chhole bhature,fastfood
21,global,gulab,5,liquid,sweet,tea,hot drink
22,italian,cluster,150,solid,spicy,pasta,fastfood
23,delhi,amul parlour,70,mixed,spicy,chhole kulche,fastfood
24,south indian,dosa seth,50,mixed,spicy,idli sambhar,healthy
25,global,NBC,50,liquid,sweet,coffee,drink
26,italian,mamus in fusion,250,mixed,neutral,lasgana,fastfood
27,global,bakery,30,solid,sweet,pastry,desert
28,global,bakery,450,solid,sweet,cakes,desert
29,chinese,roll express,50,solid,spicy,veg roll,fastfood
30,korean,seol,350,solid,spicy,kimchi,healthy

### Statistical Functions

In [47]:
df.corr()

       price
price    1.0

<img src='https://www.gstatic.com/education/formulas2/397133473/en/correlation_coefficient_formula.svg'>

In [48]:
df.corrwith(df)

price    1.0
dtype: float64

In [50]:
pd.crosstab(df['cuisine'],df['state'],)

state         liquid  mixed  solid
cuisine
USA                2      0      0
bihari             0      1      0
chinese            0      0      4
delhi              0      1      0
global             2      0      2
indian             2      0      1
italian            0      1      4
japanese           0      0      1
korean             0      0      1
mexican            0      0      1
mumbai             0      0      1
north indian       0      2      0
punjabi            1      1      0
rajasthani         0      1      0
south indian       0      1      1

In [51]:
import numpy as np

In [52]:
pd.crosstab(df['cuisine'],df['state'],df['price'],aggfunc=np.mean)

state         liquid  mixed  solid
cuisine
USA             15.0    NaN    NaN
bihari           NaN  120.0    NaN
chinese          NaN    NaN   55.0
delhi            NaN   70.0    NaN
global          27.5    NaN  240.0
indian          62.5    NaN   15.0
italian          NaN  250.0  145.0
japanese         NaN    NaN  200.0
korean           NaN    NaN  350.0
mexican          NaN    NaN  150.0
mumbai           NaN    NaN   40.0
north indian     NaN   35.0    NaN
punjabi         15.0   50.0    NaN
rajasthani       NaN  150.0    NaN
south indian     NaN   50.0   60.0

In [56]:
pd.pivot_table(df,values='price',index='type',columns='state')

state       liquid       mixed   solid
type
cold drink    15.0         NaN     NaN
desert         NaN         NaN  240.00
drink         50.0         NaN     NaN
fastfood       NaN   88.000000   99.00
healthy       62.5  106.666667  156.25
hot drink      5.0         NaN     NaN